/**
 * DO NOT EDIT THIS FILE
 * THOSE ARE JUST HELPER FUNCTIONS FOR SEASON 4
 */

import OpenAI from "openai";
import assert from 'node:assert';
import chalk from "chalk";

const ghToken = process.env["GITHUB_TOKEN"];
assert.ok(ghToken, "❌ GITHUB_TOKEN key not found");

const openai = new OpenAI({ baseURL: "https://models.github.ai/inference", apiKey: ghToken });

export async function sendUserMessageToProductivityBot(userPrompt) {
    try {
        const completion = await openai.chat.completions.create({
            model: "openai/gpt-4.1-nano",
            messages: [
                { role: "user", content: userPrompt }
            ],
        });
        const response = completion.choices[0].message?.content || "";
        return response;
    } catch (err) {
        error(`❌ Error: Failed to get completion from OpenAI: ${err.message || err} OR You may have reached the daily rate limit for GitHub Models. Please wait for the limit to reset before trying again. For more information, visit: https://gh.io/models-rate-limits`);
        return "";
    }
}

export function error(message) {
    console.error(chalk.red(message));
}
